pipeline {
    agent any

    tools {
        jdk 'Java21'
        maven 'Maven'
    }

    stages {

        stage('Build') {
            steps {
                dir('praveen') {
                bat 'mvn clean package'
                }
            }
        }

        stage('Archive WAR') {
            steps {
                archiveArtifacts artifacts: '**/target/*.war'
            }
        }
    }
}
